# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
<<<<<<< HEAD
      with:
        output: swagger-ui-output
        spec-url: https://tamlogic.asia/didonghieuvu/v2/swagger.json
    - name: "Verify swagger-ui was created"
      run: |
        test -f swagger-ui-output/index.html
        test -f swagger-ui-output/swagger-config.json
        test -f swagger-ui-output/swagger-ui-bundle.js
    - name: Upload generated Swagger UI
      uses: actions/upload-artifact@v2
      with:
        name: swagger-ui-output
        path: swagger-ui-output
=======
>>>>>>> parent of f1e7d84 (Update dotnet.yml)
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
